version: '3.8'
services:
  ui:
    build:
    #This sets the build context to the frontend directory
    #This way, the files needed for the build is gotten from the frontend directory
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    env_file:
      - .env
  backend:
    build:
      context: ./backend      
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    env_file:
      - .env
